name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14'
        
    - name: Build with Maven
      run: mvn -B package
      
    - name: Copy Jar to build
      run: cp target/*.jar build/command-api.jar && ls /build

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
   
    - name: Build the Docker image
      run: docker build . --file \build/Dockerfile --tag tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }}
