name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: '14'
        
    - name: Build with Maven
      run: mvn -B package
      
    - name: Copy Jar to build
      run: mkdir jar && cp target/*.jar jar/command-api.jar

    - name: Set Release version env variable
      run: |
        echo "RELEASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
    - name: Upload jar
      uses: actions/upload-artifact@v1
      with:
        name: jarpack
        path: ./jar

   
  deploy:
    name: Deploy
    needs: [build]
    runs-on: ubuntu-latest
    steps:
    - name: Download jar
      uses: actions/download-artifact@v1
      with:
        name: jarpack
        path: ./jar
    - name: DEBUG
      run: ls && cd jar && ls
    - name: Build the Docker image
      run: docker build . --file \build/Dockerfile --tag tag365/tm-streams-support-api:${{ env.RELEASE_VERSION }}
